### ISSUE TITLE
from cnn_utils import *

### ISSUE THREAD

**Issue by IdelCoder** [shaoanlu/deeplearning.ai-Convolutional-Neural-Networks#2]
Somehow cnn_utils is not a python module. How can I access it?

**Comment by IdelCoder** [comment]
I found the solution. In fact, the **cnn_utils** is **tf_utils** from Week 3 of Andrew Ng's 2nd course of his Deep Learning Specialisation series: Improving Deep Neural Networks: Hyperparameter tuning, Regularization and Optimization. For quick accessing to tf_utils.py and the dataset , you can refer to [https://github.com/aslisabanci/coursera-tensorflowTutorial](https://github.com/aslisabanci/coursera-tensorflowTutorial).

**Comment by ggardu** [comment]
The link that you gave is no longer existing.
Do you have something else ?
Thanks

**Comment by bonastreyair** [comment]
[cnn_utils.zip](https://github.com/shaoanlu/deeplearning.ai-Convolutional-Neural-Networks/files/2162974/cnn_utils.zip)
here you have them

**Comment by ggardu** [comment]
I would like to thank you very much and for your time.
This worked.

**Comment by joelvinaykumar** [comment]
Hey, I couldn't install with zip. It says
```

Processing ./cnn_utils.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-j_iz_tec/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-j_iz_tec/
```
